name: lab4
services:
  nginx:
    image: "nginx:1.27.2"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html

  flask:
    image: "tolaykinsi/flask:1.0"
    container_name: flask
    environment:
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=True
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - postgres

  postgres:
    image: "postgres:16.4-alpine"
    container_name: postgres
    env_file:
      - postgres.env
    secrets:
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

secrets:
  db_password:
    file: ./db_password

volumes:
  postgres_data: